name: Scan Repos for Open PRs

on:
  schedule:
    - cron: '0 10 * * 1-5' # At 10:00 AM on Monday to Friday
  workflow_dispatch:

jobs:
  scanPRs:
    runs-on: ubuntu-latest
    steps:
      - name: Check for open PRs
        run: |
          # Get list of repos
          REPOS=$(curl -H "Authorization: token $TOKEN" https://api.github.com/orgs/$YOUR_ORG_NAME/repos | jq -r '.[].full_name')
          echo "List of repos: $REPOS"

          # For each repo, check for open PRs
          for REPO in $REPOS; do
              echo "Current repo: $REPO"
              PRS=$(curl -H "Authorization: token $TOKEN" https://api.github.com/repos/$REPO/pulls)
              COUNT=$(echo $PRS | jq '. | length')
              echo "Number of opened PRs: $COUNT"

              if [ "$COUNT" -gt 0 ]; then
                  echo "Sending Teams notification for repo $REPO with $COUNT open PRs."

                  # Loop through each PR and get its number
                  for i in $(seq 0 $(($COUNT - 1))); do
                      PR_NUMBER=$(echo $PRS | jq ".[$i].number")   
                      echo "PR_NUMBER: $PR_NUMBER"
                      PR_TITLE=$(echo $PRS | jq -r ".[$i].title")
                      echo "PR_TITLE: $PR_TITLE"
          
                      # Craft your message body for Teams here
                      MESSAGE_BODY='{
                          "@type": "MessageCard",
                          "@context": "http://schema.org/extensions",
                          "title": "Open PR Alert",
                          "text": "Repo '$REPO' has an open PR $PR_NUMBER titled: '$PR_TITLE'."
                      }'

                      # Send the message to Teams
                      echo "MESSAGE_BODY: $MESSAGE_BODY"
                      curl -H "Content-Type: application/json" -d "$MESSAGE_BODY" ${{ secrets.TEAMS_WEBHOOK_URL }}
                  done
              fi
          done
        env:
          YOUR_ORG_NAME: CodeDeiOrg
          TOKEN: ${{ secrets.PAT_TOKEN }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
